$schema: "http://json-schema.org/draft-04/schema#"
description: snakemake configuration file
type: object
properties:
  samples:
    type: string
  units:
    type: string
  resources:
    type: string
    description: Path to resources.yaml file
  default_container:
    type: string
    description: name or path to a default docker/singularity container
  reference:
    type: object
    properties:
      twist_dna_st_artifacts:
        type: string
        description: artifact file for twist dna st
      twist_dna_st_background_panel:
        type: string
        description: backgound noise file for twist dna st
  required:
    - samples
    - units
    - resources
    - default_container

  hrd:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for hrd
      container:
        type: string
        description: name or path to docker/singularity container

  msisensor_pro:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for msisensor_pro
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded to msisensor_pro
      PoN:
        type: string
        description: path to panel of normals
    required:
      - PoN

  optitype:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for optitype
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded to optitype
      sample_type:
        type: string
        description: -d for dna and -r for rna
      enumeration:
        type: integer
        description: number of output HLA-types, 1 equals output only the best

  scarhrd:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for tmb
      container:
        type: string
        description: name or path to docker/singularity container
      reference_name:
        type: string
        description: references name (grch37, grch38)
      seqz:
        type: boolean
        description: If sequeze file is produced by Sequenza or not (FALSE, TRUE)

  tmb:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for tmb
      container:
        type: string
        description: name or path to docker/singularity container
      filter_nr_observations:
        type: integer
        description: Filter all variants that has been observed before >= X times in artifact file
      dp_limit:
        type: integer
        description: Filter all variants with depth < X
      vd_limit:
        type: integer
        description: Filter all variants with variants reads < X
      af_lower_limit:
        type: number
        description: Filter all variants with MAF < X
      af_upper_limit:
        type: number
        description: Filter all variants with MAF > X
      gnomad_limit:
        type: number
        description: Filter all variants with found in GnomAD witn MAF > X
      db1000g_limit:
        type: number
        description: Filter all variants with found in 1000 Genomes witn MAF > X
      background_sd_limit:
        type: integer
        description: Filter all variants with background levels < X standard deviation away
      nssnv_tmb_correction:
        type: number
        description: Design dependent correction factor to get TMB representative for the entire genome
      nssnv_ssnv_tmb_correction:
        type: number
        description: Design dependent correction factor to get TMB representative for the entire genome
