$schema: "http://json-schema.org/draft-04/schema#"
description: snakemake configuration file
type: object
properties:
  samples:
    type: string
  units:
    type: string
  resources:
    type: string
    description: Path to resources.yaml file
  default_container:
    type: string
    description: name or path to a default docker/singularity container
  reference:
    type: object
    properties:
      twist_dna_st_artifacts:
        type: string
        description: artifact file for twist dna st
      twist_dna_st_background_panel:
        type: string
        description: backgound noise file for twist dna st
  required:
    - samples
    - units
    - resources
    - default_container

  msisensor_pro:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for msisensor_pro
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded to msisensor_pro
      PoN:
        type: string
        description: path to panel of normals
    required:
      - PoN

  tmb:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for tmb
      container:
        type: string
        description: name or path to docker/singularity container
      filter_nr_observations:
        type: integer
        description: Filter all variants that has been observed before >= X times in artifact file

  hrd:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for hrd
      container:
        type: string
        description: name or path to docker/singularity container
