$schema: "http://json-schema.org/draft-04/schema#"
description: snakemake configuration file
type: object
properties:
  resources:
    type: string
    description: Path to resources.yaml file
  samples:
    type: string
    description: path to samples.tsv file
  units:
    type: string
    description: path to units.tsv file
  default_container:
    type: string
    description: name or path to a default docker/singularity container
  reference:
    type: object
    properties:
      twist_dna_st_artifacts:
        type: string
        description: artifact file for twist dna st
      twist_dna_st_background_panel:
        type: string
        description: background noise file for twist dna st

  required:
    - default_container
    - resources
    - samples
    - units

  cnvkit2scarhrd:
    type: object
    description: parameters for cnvkit2scarhrd
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container

  finaletoolkit_end_motifs:
    type: object
    description: parameters for finaletoolkit_end_motifs
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded

  fix_scarhrd_output:
    type: object
    description: parameters for fix_scarhrd_output
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container

  msisensor_pro:
    type: object
    description: parameters for msisensor_pro
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded

  msisensor_pro_filter_sites:
    type: object
    description: parameters for msisensor_pro_filter_sites
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      msi_sites:
        type: string
        description: Bed file for choosing specific msi sites to analyze. Set to empty string for no filtering.

  optitype:
    type: object
    description: parameters for optitype
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded
      sample_type:
        type: string
        description: -d for dna and -r for rna
      enumeration:
        type: integer
        description: number of output HLA-types, 1 equals output only the best

  scarhrd:
    type: object
    description: parameters for scarhrd
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      reference_name:
        type: string
        description: references name (grch37, grch38)
      seqz:
        type: boolean
        description: if sequeze file is produced by Sequenza or not (False, True)

  tmb:
    type: object
    description: parameters for tmb
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      af_lower_limit:
        type: number
        description: filter all variants with MAF < af_lower_limit
      af_upper_limit:
        type: number
        description: filter all variants with MAF > af_upper_limit
      af_germline_lower_limit:
        type: number
        description: filter all variants with af_germline_lower_limit > MAF < af_germline_upper_limit
      af_germline_upper_limit:
        type: number
        description: filter all variants with af_germline_lower_limit > MAF < af_germline_upper_limit
      artifacts:
        type: string
        description: file with artifact info created by the reference module. Set to empty string to skip, which is the default setting.
      background_panel:
        type: string
        description: file with background noise info created by the reference module. Set to empty string to skip, which is the default setting.
      background_sd_limit:
        type: integer
        description: filter all variants that are closer than background_sd_limit standard deviations from the background median noise. Set to arbitrary value if artifact file is not used.
      db1000g_limit:
        type: number
        description: filter all variants with found in 1000 Genomes witn MAF > db1000g_limit
      dp_limit:
        type: integer
        description: filter all variants with depth < dp_limit
      filter_genes:
        type: string
        description: path to file with gene names where variants should be filter out
      filter_nr_observations:
        type: integer
        description: filter all variants that has been observed before >= filter_nr_observations times in artifact file. Set to arbitrary value if artifact file is not used.
      filter_regions:
        type: array
        description: list of bedfiles
        items:
          type: string
          description: BED file with chromosomal regions that are used to filter out potential artifact variants
      gnomad_limit:
        type: number
        description: filter all variants with found in GnomAD witn MAF > gnomad_limit
      nr_avg_germline_snvs:
        type: number
        description: design dependent TMB correction term dependent on the average number of variants found in normal samples
      nssnv_tmb_correction:
        type: number
        description: design dependent TMB correction factor dependent on design size or correlation to commercial panels like TSO500
      variant_type_list:
        type: array
        description: list of variant types
        items:
          type: string
          description: Variant types that should be included in the in the TMB calculations ("missense_variant", "synonymous_variant", "stop_gained", "stop_lost")
      vd_limit:
        type: integer
        description: filter all variants with variants reads < vd_limit

