resources: "resources.yaml"
samples: "samples.tsv"
units: "units.tsv"

default_container: "docker://marrip/common:1.1.0"

reference:
  background: "references/background_panel_small.tsv"
  vardict_artifacts: "references/Vardict_artifact_positions_small.txt"

msisensor_pro:
  container: "docker://hydragenetics/msisensor_pro:1.2.0"
  PoN: "references/Msisensor_pro_reference.list_baseline"

tmb:
  container: "docker://python:3.9.7-slim"
