resources: "resources.yaml"
samples: "samples.tsv"
units: "units.tsv"

default_container: "docker://hydragenetics/common:0.0.1"

reference:
  background: "references/background_panel_small.tsv"
  artifacts: "references/artifact_positions_chr1.txt"

msisensor_pro:
  container: "docker://hydragenetics/msisensor_pro:1.2.0"
  PoN: "references/Msisensor_pro_reference.list_baseline"

tmb:
  container: "docker://python:3.9.7-slim"

hrd:
  container: "docker://hydragenetics/common:0.0.1"
