resources: "resources.yaml"
samples: "samples.tsv"
units: "units.tsv"

default_container: "docker://marrip/common:1.1.0"

msisensor_pro:
  container: "docker://gmsuppsala/somatic:develop"
  PoN: "references/Msisensor_pro_reference.list_baseline"
