---

resources: "resources.yaml"
samples: "samples.tsv"
units: "units.tsv"

default_container: "docker://hydragenetics/common:0.1.9"

trimmer_software: None

bwa_mem:
  container: "docker://hydragenetics/bwa_mem:0.7.17"
  amb: "reference/hg19.fasta.amb"
  ann: "reference/hg19.fasta.ann"
  bwt: "reference/hg19.fasta.bwt"
  pac: "reference/hg19.fasta.pac"
  sa: "reference/hg19.fasta.sa"

bcbio_variation_recall_ensemble:
  container: "docker://hydragenetics/bcbio-vc:0.2.6"
  callers:
    - vardict
    - gatk_mutect2

cnvkit_batch:
  container: "docker://hydragenetics/cnvkit:0.9.9"
  normal_reference: "reference/cnvkit_nextseq_36.cnn"
  method: "hybrid"

cnvkit_batch_hrd:
  container: "docker://hydragenetics/cnvkit:0.9.9"
  normal_reference_hrd: "reference/cnvkit_nextseq_27_HRD.cnn"
  method: "hybrid"

hotspot_annotation:
  hotspots: "reference/Hotspots_combined_regions_nodups.csv"
  chr_translation_file: "reference/hotspot_report.chr.translation.hg19"

reference:
  fasta: "reference/hg19.fasta"
  background: "reference/background_panel_small.tsv"
  artifacts: "reference/artifact_positions_chr1.txt"

optitype:
  #container: "docker://hydragenetics/optitype:1.3.5"
  container: "docker://fred2/optitype"
  sample_type: "-d"
  enumeration: 2

msisensor_pro:
  container: "docker://hydragenetics/msisensor_pro:1.2.0"
  PoN: "reference/Msisensor_pro_reference.list_baseline"

scarhrd:
  container: "docker://hydragenetics/scarhrd:20200825"
  reference_name: "grch37"
  seqz: False

tmb:
  container: "docker://python:3.9.7-slim"

vep:
  container: "docker://hydragenetics/vep:105"
  vep_cache:  "vep/"
  mode: --offline --cache
  extra: " --assembly GRCh37 --check_existing --pick --sift b --polyphen b --ccds --uniprot --hgvs --symbol --numbers --domains --regulatory --canonical --protein --biotype --uniprot --tsl --appris --gene_phenotype --af --af_1kg --af_gnomad --max_af --pubmed --variant_class "
