from hydra_genetics.utils.resources import load_resources

import re


rule all:
    input:
        "biomarker/scarhrd/HD832.HES45_T.pathology.scarhrd_cnvkit_score.txt",
        "biomarker/msisensor_pro/HD832.HES45_T",
        "biomarker/tmb/HD832.HES45_T.TMB.txt",


configfile: "config.yaml"


config = load_resources(config, config["resources"])


# prealignment and cnv_sv are pulled from their migration branches instead of the release tags
# recorded in README.md: every released tag of both annotates functions with
# snakemake.io.Wildcards, which Snakemake 9 no longer provides, so they cannot even be parsed.
# alignment and annotation stay on their release tags - they parse under Snakemake 9 as-is.
# TODO: move prealignment and cnv_sv back to tag=extract_module_version_from_readme(...) once
# they publish Snakemake 9 releases, and record the version pairs in COMPATIBILITY.md.
SNAKEMAKE9_BRANCH = "migrate-to-snakemake9"


def extract_module_version_from_readme(modulename):
    search_string = modulename + ":(.+)\n$"
    with open("../../README.md", "r") as reader:
        for line in reader:
            result = re.search(search_string, line)
            if result:
                return result[1]


module prealignment:
    snakefile:
        github(
            "hydra-genetics/prealignment",
            path="workflow/Snakefile",
            branch=SNAKEMAKE9_BRANCH,
        )
    config:
        config


use rule * from prealignment as prealignment_*


module alignment:
    snakefile:
        github(
            "hydra-genetics/alignment",
            path="workflow/Snakefile",
            tag=extract_module_version_from_readme("alignment"),
        )
    config:
        config


use rule * from alignment as alignment_*


module annotation:
    snakefile:
        github(
            "hydra-genetics/annotation",
            path="workflow/Snakefile",
            tag=extract_module_version_from_readme("annotation"),
        )
    config:
        config


use rule * from annotation as annotation_*


module cnv_sv:
    snakefile:
        github(
            "hydra-genetics/cnv_sv",
            path="workflow/Snakefile",
            branch=SNAKEMAKE9_BRANCH,
        )
    config:
        config


use rule * from cnv_sv as cnv_sv_*


module biomarker:
    snakefile:
        "../../workflow/Snakefile"
    config:
        config


use rule * from biomarker as biomarker_*
